Map<String, String> assetsMap = {
  'bg': '/assets/bg.png',
  'logo': '/assets/logo.png',
  'blink': '/assets/blink.png',
  'candy': '/assets/candy.png',
  'bomb': '/assets/bomb.png',
  'lock': '/assets/lock.png',
  'cart_front_1': '/assets/basket/cart-front-1.png',
  'cart_back_1': '/assets/basket/cart-back-1.png',
  'level_1_bg': '/assets/bg/level-1.png',
  'level_2_bg': '/assets/bg/level-2.png',
  'level_3_bg': '/assets/bg/level-3.png',
  'level_4_bg': '/assets/bg/level-4.png',
  'level_1_preview': '/assets/bg/preview_level_1.png',
  'level_2_preview': '/assets/bg/preview_level_2.png',
  'level_3_preview': '/assets/bg/preview_level_3.png',
  'level_4_preview': '/assets/bg/preview_level_4.png',
  'start_btn': '/assets/buttons/start_btn.png',
  'settings_btn': '/assets/buttons/settings_btn.png',
  'settings_icon': '/assets/buttons/settings_icon.png',
  'restart_btn': '/assets/buttons/restart_btn.png',
  'privacy_btn': '/assets/buttons/privacy_btn.png',
  'exit_btn': '/assets/buttons/exit_btn.png',
  'back_btn': '/assets/buttons/back_btn.png',
  'checkbox_enable': '/assets/buttons/checkbox_enable.png',
  'checkbox_disable': '/assets/buttons/checkbox_disable.png',
  'lose_bg': '/assets/bg/lose_bg.png',
  'privacy_bg': '/assets/bg/privacy_bg.png',
  'settings_bg': '/assets/bg/settings_bg.png',
  'update_bg': '/assets/bg/update_bg.png',
  'win_bg': '/assets/bg/win_bg.png',
  'sweet_1': '/assets/items/sweet_1.png',
  'sweet_2': '/assets/items/sweet_2.png',
  'sweet_3': '/assets/items/sweet_3.png',
  'sweet_4': '/assets/items/sweet_4.png',
  'sweet_5': '/assets/items/sweet_5.png',
  'sweet_6': '/assets/items/sweet_6.png',
  'sweet_7': '/assets/items/sweet_7.png',
  'sweet_8': '/assets/items/sweet_8.png',
  'sweet_9': '/assets/items/sweet_9.png',
  'sweet_10': '/assets/items/sweet_10.png',
  'sweet_11': '/assets/items/sweet_11.png',
};

Map<String, String> soundsMap = {
  'background_sound': '/assets/music/background.mp3',
  'boom_sound': '/assets/music/boom.mp3',
  'buttons_sound': '/assets/music/buttons.mp3',
  'gun_sound': '/assets/music/gun.mp3',
};