Map<String, String> assetsMap = {
  'bg': '/assets/images/bg.png',
  // 'logo': '/assets/images/logo.png',
  'level_1_bg': '/assets/images/levels/level_1_bg.png',
  'level_2_bg': '/assets/images/levels/level_2_bg.png',
  'level_3_bg': '/assets/images/levels/level_3_bg.png',
  'level_4_bg': '/assets/images/levels/level_4_bg.png',
  'level_1_preview': '/assets/images/levels/level_1_preview.png',
  'level_2_preview': '/assets/images/levels/level_2_preview.png',
  'level_3_preview': '/assets/images/levels/level_3_preview.png',
  'level_4_preview': '/assets/images/levels/level_4_preview.png',
  'back_btn': '/assets/images/buttons/back_btn.png',
  'home_btn': '/assets/images/buttons/home_btn.png',
  'play_btn': '/assets/images/buttons/play_btn.png',
  'again_btn': '/assets/images/buttons/again_btn.png',
  'reboot_btn': '/assets/images/buttons/rebot_btn.png',
  'settings_btn': '/assets/images/buttons/settings_btn.png',
  'left_menu_btn': '/assets/images/buttons/left_menu_btn.png',
  'right_menu_btn': '/assets/images/buttons/right_menu_btn.png',
  'main_menu_btn': '/assets/images/buttons/main_menu_btn.png',
  'ball_decoration': '/assets/images/elements/ball_decoration.png',
  'ball_icon': '/assets/images/elements/ball_icon.png',
  'coin_icon': '/assets/images/elements/coin_icon.png',
  'filled_star': '/assets/images/elements/filled_star.png',
  'stars': '/assets/images/elements/stars.png',
  'gun': '/assets/images/elements/gun.png',
  'gun_back': '/assets/images/elements/gun_back.png',
  'ball': '/assets/images/elements/ball.png',
  'boom': '/assets/images/elements/boom.png',
  'settings_decoration': '/assets/images/elements/settings_decoration.png',
  'update_decoration': '/assets/images/elements/update_decoration.png',
  'checkbox_active': '/assets/images/elements/checkbox_active.png',
  'checkbox_disable': '/assets/images/elements/checkbox_disable.png',
  'win_decoration': '/assets/images/elements/win_decoration.png',
  'lose_decoration': '/assets/images/elements/lose_decoration.png',
  'lock': '/assets/images/elements/lock.png',
  'planet_1': '/assets/images/planets_sprite/planet_1.png',
  'planet_2': '/assets/images/planets_sprite/planet_2.png',
  'planet_3': '/assets/images/planets_sprite/planet_3.png',
  'planet_4': '/assets/images/planets_sprite/planet_4.png',
  'planet_5': '/assets/images/planets_sprite/planet_5.png',
  'planet_6': '/assets/images/planets_sprite/planet_6.png',
  'planet_7': '/assets/images/planets_sprite/planet_7.png',
  'planet_8': '/assets/images/planets_sprite/planet_8.png',
  'planet_9': '/assets/images/planets_sprite/planet_9.png',
  'planet_10': '/assets/images/planets_sprite/planet_10.png',
};

Map<String, String> soundsMap = {
  'background_sound': '/assets/music/background.mp3',
  'boom_sound': '/assets/music/boom.mp3',
  'buttons_sound': '/assets/music/buttons.mp3',
  'gun_sound': '/assets/music/gun.mp3',
};